Milestone 4: Desktop and responsive
belalgamal46/Setup-and-mobile-first pull request #4
Opened 2022-09-29 16:17 UTC by belalgamal46

### Milestone 4 Desktop and Responsive
  - Create media queries
  - Update HTML
  - Change image for desktop
  - Update styles.css to be responsive by changing CSS properties

2022-09-29 16:40 UTC, christianbiring1 requested changes
Hi @belalgamal46 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/193089297-494391d9-49bc-45ca-987b-eb071a0a9d46.gif)

## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary`
- [ ] The design is great :+1: :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 16:40 UTC, christianbiring1 commented on CSS/styles.css
> +  .card-works:nth-child(2),
- [ ]  Kindly make sure your cards are responsive and have enough width on the screen of `768px---1024px`. 
As you can see how they look like on your design :point_down: 
![Screenshot from 2022-09-29 18-27-27](https://user-images.githubusercontent.com/97100091/193088086-ef44fcd4-9c26-47d8-8a44-357a07ba937a.png)

2022-09-29 16:40 UTC, christianbiring1 commented on CSS/styles.css
> +    display: initial;
- [ ] Kindly make sure your body also has a similar color to the design provided in Figma.

2022-09-29 16:40 UTC, christianbiring1 commented on index.html
> +              <button type="button" class="btn">See Project</button>
- [ ] Kindly make sure also you implement the button interactions like `hover`, `disable`, and `active` as the Figma design

2022-09-30 01:44 UTC, Santiago220991 requested changes
Hi @belalgamal46,
I'm Santiago your code reviewer for this PR. :wave: :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

 ## Highlights
:heavy_check_mark: Followed GitHub flow.
:heavy_check_mark: No linter errors.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 01:44 UTC, Santiago220991 commented on CSS/styles.css
> +  flex-direction: column;
Kindly make sure that your project sticks as much as possible to the Figma design provided. Please reduce the space between your about section and the contact form.  :eyes :eyes: 

![image](https://user-images.githubusercontent.com/98363075/193170263-29155a23-1212-4ac3-9708-9bf2aa19e10a.png)

2022-09-30 01:44 UTC, Santiago220991 commented on CSS/styles.css
>  }
[OPTIONAL] As the [last code reviewer suggested](https://github.com/belalgamal46/Setup-and-mobile-first/pull/4#discussion_r983773217) please make sure that you are adding interactions to the buttons according to Figma template provided. The hover effect means that when you put the cursor over the button it changes its color, this feature is not working. Kindly fix the hover effect on the rest of the buttons in your project. :pray: :pray: 
![image](https://user-images.githubusercontent.com/98363075/193171016-4362958b-f66c-43ec-87fb-40bdd9bba3c5.png)

2022-09-30 01:44 UTC, Santiago220991 commented on index.html
>          </div>
- [OPTIONAL] Kindly make sure that your links are working and redirect the user to the different sections of your project. :+1: :smiley: :smiley:

2022-09-30 02:06 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @belalgamal46 , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 02:28 UTC, merged

2022-09-30 07:35 UTC, manq2010 commented
Your website looks clean and neat :clap:  Perhaps you could look into reducing the transition time on the effects. :+1:

2022-09-30 12:23 UTC, Serengia commented
I like how clean your site looks. [OPTIONALLY]: You could perhaps increase the minimum font of the description on your cards to 16px. That way you will improve the readability of the text to everyone including those with poor vision. Again, great job! 

---
![200](https://user-images.githubusercontent.com/69452516/193268414-6018de8e-f6b6-46ec-acbf-9e97e2585248.gif)

2022-10-01 14:05 UTC, jodavid444 commented
Your website looks good.